### ISSUE TITLE
OSCAL go library

### ISSUE THREAD

**Issue by JonZeolla** [cloud-native-security-controls/controls-catalog#27]

**Comment by brandtkeller** [comment]
Wanted to leave a note here that we've been making some progress on this library.

Link: https://github.com/defenseunicorns/go-oscal

Currently exposes data types from `1.0.4` up to the latest release `1.1.2`. 

- Creates and manages go-lang datatypes for all OSCAL models
- Contains functionality for validating OSCAL artifacts for schema compliance
- Contains functionality for upgrading OSCAL artifacts from one version of OSCAL to another.

**Comment by brandtkeller** [comment]
@JonZeolla I don't have any current functionality for CSV to Catalog creation but wouldn't be against that adaptation if it were deemed valuable. Let me know if you have any ideas for what else we might look to explore here.
