### ISSUE TITLE
Address controls list v1.0 feedback

### ISSUE THREAD

**Issue by JonZeolla** [cloud-native-security-controls/controls-catalog#6]
Address the feedback we've received on phase 1.0 of the controls list.

- The scope of some controls is not always clear. Sometimes they sound ambiguous
- There are redundancies: some controls seem very similar, across sections.
- I am a security engineer, but looking at the target audience, I think many of them might have trouble understanding a lot of the controls and what they imply from an implementation perspective. I think a lot more guidance is required.
- In general, the list is huge. Maybe there is a way to break this into smaller chunks, e.g. grouped by maturity level. In it's current form, it might be intimidating for people willing to start establishing compliance to this controls catalog.
- More details [here](https://drive.google.com/file/d/1CLbNJ3uDHfVF7XuxYxl3rByGzaNTgrBw/view?usp=sharing)

**Comment by stenio123** [comment]
@stenio123 will take a stab at this

**Comment by stenio123** [comment]
Ok, I addressed the feedback here:
https://drive.google.com/file/d/1zTmlpXZezjoQJrA7LzYIjO2yFen72SsJ/view?usp=sharing

Having issues with git/excel at work, will create a PR for the few changes I made to the csv later today.

**Comment by JonZeolla** [comment]
@stenio123 it seems like versioning in the filename is going to quickly get us out of sync; thoughts on using a GitHub release and rename the file to `controls/controls_catalog.csv`?  I can handle the release

**Comment by JonZeolla** [comment]
https://github.com/cloud-native-security-controls/controls-catalog/releases/tag/v1.0.0
